import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth/next'
import { authOptions } from './api/auth/[...nextauth]/route'
import SessionProvider from './SessionProvider'
import Login from './components/Login'
import GlobalProvider from './Context/GlobalContext'
import Sidebar from './components/Sidebar'
import Header from './components/Header'
import DialogAndModalProvider from './Context/DialogAndModalContext'
import SideDialog from './components/SideDialog'
import { ToastContainer,Slide, Zoom, Flip, Bounce } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <GlobalProvider>
            <DialogAndModalProvider>
              {!session ? (<Login />) : (
                <div className='flex overflow-y-auto '>
                  <Sidebar />
                  <SideDialog />
                  <div className='flex-1 flex-col h-screen relative'>
                    <Header />
                    <main className=''>{children}</main>
                  </div>
                </div>
              )}
            </DialogAndModalProvider>
          </GlobalProvider>
        </SessionProvider>
        <ToastContainer position="top-center" theme="dark" autoClose={1000} limit={1} transition={Zoom}/>
      </body>
    </html>
  )
}
